version: '3.9'

services:
  db:
    image: postgres:13
    env_file:
      - .env
    expose:
      - '5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', '-c', 'pg_isready -U $POSTGRES_USER']
      interval: 10s
      retries: 5
      timeout: 5s
    restart: on-failure

  app:
    build: .
    env_file:
      - .env
    tty: true
    ports:
      - '8000:8000'
    command: sh -c 'python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    restart: on-failure

  redis:
    image: redis:latest
    restart: on-failure
    expose:
      - '6379'

  celery:
    build: .
    env_file:
      - .env
    tty: true
    command: sh -c 'celery -A config worker --beat --scheduler django --loglevel=info'
    depends_on:
      - redis
      - db
      - app
    volumes:
      - .:/app
    restart: on-failure

volumes:
  pg_data: